# Generated by Django 2.2.4 on 2019-09-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrgBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('RegistrationDate', models.DateField()),
                ('PR', models.CharField(max_length=300)),
                ('Url', models.URLField(max_length=50)),
                ('Affiliation', models.CharField(max_length=50)),
                ('ContactPerson', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Telephone', models.CharField(max_length=12)),
                ('Region', models.CharField(blank=True, choices=[('Addis Ababba', 'Addis Ababba'), ('Johannesburg', 'Johannesburg'), ('Something', 'Something')], max_length=30)),
                ('Industry', models.ManyToManyField(to='index.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=200)),
                ('Contents', models.CharField(max_length=300)),
                ('OrgName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo')),
                ('ServiceCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.ServiceCategory')),
            ],
        ),
        migrations.AddField(
            model_name='orgbaseinfo',
            name='ServiceCategory',
            field=models.ManyToManyField(to='index.ServiceCategory'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Large', models.IntegerField()),
                ('Medium', models.IntegerField()),
                ('SmallandMicro', models.IntegerField()),
                ('OrgName', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents', models.CharField(max_length=300)),
                ('Result', models.CharField(max_length=300)),
                ('OrgName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo')),
                ('ServiceCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.ServiceCategory')),
            ],
        ),
    ]
