# Generated by Django 2.2.3 on 2019-10-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ServiceCategory',
        ),
        migrations.AddField(
            model_name='service',
            name='ServiceCategory',
            field=models.ManyToManyField(to='index.ServiceCategory'),
        ),
    ]
