# Generated by Django 2.2.4 on 2019-08-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('ada', 'Addis Adabba'), ('jhn', 'Johannesburg'), ('smt', 'Something')], default='ada', help_text='Region of the company', max_length=3),
        ),
    ]
