# Generated by Django 2.2.4 on 2019-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_orgbaseinfo_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgbaseinfo',
            name='Industry',
        ),
        migrations.AddField(
            model_name='orgbaseinfo',
            name='Industry',
            field=models.ManyToManyField(to='index.Industry'),
        ),
    ]
