# Generated by Django 2.2.3 on 2019-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191007_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='ServiceCategory',
        ),
        migrations.AddField(
            model_name='case',
            name='ServiceCategory',
            field=models.ManyToManyField(to='index.ServiceCategory'),
        ),
    ]
