# Generated by Django 2.2.4 on 2019-09-03 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190830_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='OrgName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo', unique=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('ada', 'Addis Ababa'), ('jhn', 'Johannesburg'), ('smt', 'Something')], default='ada', help_text='Region of the company', max_length=3),
        ),
    ]
