# Generated by Django 2.2.3 on 2019-10-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20191010_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbaseinfo',
            name='OfficeHour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Contents',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='Result',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Large',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Medium',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='SmallandMicro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Affiliation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='ContactPerson',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='PR',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='RegistrationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Url',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Contents',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='Service',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
