# Generated by Django 2.2.4 on 2019-09-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190903_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='OrgName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo'),
        ),
    ]
