# Generated by Django 2.2.3 on 2019-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20191013_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('Addis Ababba', 'Addis Ababba'), ('Afar', 'Afar'), ('Amhara', 'Amhara'), ('Benishangul-Gumuz', 'Benishangul-Gumuz'), ('Dire Dawa', 'Dire Dawa'), ('Gambela', 'Gambela'), ('Harari', 'Harari'), ('Oromia', 'Oromia'), ('Somali', 'Somali'), ('Tigray', 'Tigray')], max_length=30, null=True),
        ),
    ]
