# Generated by Django 2.2.4 on 2019-09-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190920_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='OrgName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.OrgBaseInfo'),
        ),
    ]
