# Generated by Django 2.2.4 on 2019-10-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20191015_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCompanySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='orgbaseinfo',
            name='TargetCompanySize',
            field=models.ManyToManyField(to='index.TargetCompanySize'),
        ),
    ]
