# Generated by Django 2.2.4 on 2019-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190921_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('Addis Ababba', 'Addis babba'), ('Johannesburg', 'Johannesburghn'), ('Something', 'Something')], default='ada', help_text='Region of the company', max_length=30),
        ),
    ]
