# Generated by Django 2.2.4 on 2019-09-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190922_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Region',
            field=models.CharField(blank=True, choices=[('Addis Ababba', 'Addis Ababba'), ('Johannesburg', 'Johannesburg'), ('Something', 'Something')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orgbaseinfo',
            name='Telephone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
